name: Deploy to Azure VM

on:
  push:
    branches:
      - main
    paths:
      - 'BackEnd/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.SSH_HOST}}
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/azureuser/PostHive
            git fetch origin main
            git reset --hard origin/main
            cd BackEnd
            npm install
            pm2 restart posthive-backend --update-env || pm2 start src/index.js
